'use client'

import {ChineseTitle,Localize,useSiteLanguage} from "@/components/site-language"
import { ChapterRail } from "@/components/chapter-rail"
import Image from 'next/image'
import Link from 'next/link'
import {useState,useLayoutEffect,useRef,createContext,useContext,type ReactNode} from 'react'
import translations from './zh.json'
import {ResearchIntro} from './research'
const LanguageContext=createContext(false)
function useTranslation(){const zh=useContext(LanguageContext);return (text:string)=>zh ? (translations as Record<string,string>)[text] ?? text : text}
import {motion,useReducedMotion} from 'framer-motion'
import './style.css'
const path='/ecdysis/'
function Reveal({children}:{children:ReactNode}){const r=useReducedMotion();return <motion.div initial={{opacity:0,y:r?0:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.1}} transition={{duration:.65,ease:'easeOut'}}>{children}</motion.div>}
function Photo({src,alt,caption,className}:{src:string;alt:string;caption?:string;className?:string}){const t=useTranslation();return <figure className={`ec-photo${className?` ${className}`:''}`}><a href={`${path}${src}.webp`} target="_blank" rel="noreferrer" aria-label={`${t("Enlarge")}: ${t(alt)}`}><Image src={`${path}${src}.webp`} width={1600} height={1200} sizes="(max-width:760px) 100vw, 60vw" alt={t(alt)}/></a>{caption&&<figcaption>{t(caption)}</figcaption>}</figure>}
function Heading({n,title,children}:{n:string;title:string;children?:ReactNode}){const t=useTranslation();return <div className="ec-heading"><span className="ec-label">{t(n)}</span><h2><ChineseTitle>{t(title)}</ChineseTitle></h2>{children&&<p>{typeof children === "string" ? t(children) : children}</p>}</div>}
const modules=[{title:'Sense',tag:'01 / Detection prototype',text:'Bring skin imaging and physiological signals into one interaction. A macro camera, sensing module and on-device prompts explore how a routine check can become easier to follow.'},{title:'Respond',tag:'02 / Material exploration',text:'Explore hydrogel printing as a physical feedback format. Custom shapes and colours offer different ways to make a care object feel personal.'},{title:'Reflect',tag:'03 / Digital concept',text:'Make records and trends accessible through a companion interface. Personalised prediction is a future research direction, rather than a trained capability of the prototype.'}]
const systemVisuals=[
 {media:[{src:'/ecdysis/system-sense.jpg',alt:'Using the Ecdysis device to sense a skin area'}]},
 {media:[{src:'/ecdysis/system-respond.jpg',alt:'Drawing a personalised physical response in the companion interface'},{src:'/ecdysis/printing.webp',alt:'Hydrogel extrusion experiment on an Eazao Bio printer'}]},
 {media:[{src:'/ecdysis/system-reflect.jpg',alt:'Ecdysis interface screens for reviewing records and trends'}]}
]
const sensingPanels=[
 {title:'Visual recognition',tag:'01 / IMAGE',image:'/ecdysis/vision-recognition.jpg',alt:'Prototype comparison between a visibly irritated skin image and a normal skin image',text:'The WX2070 captures a close-up image. OpenCV then converts the colour space, detects edges and segments the region of interest before rule-based comparison of redness and raised texture.'},
 {title:'Physiological sensing',tag:'02 / SIGNALS',image:'/ecdysis/hardware.webp',alt:'SY-HRV-TEMP physiological sensing module used in the prototype',text:'The SY-HRV-TEMP module and ESP32 collect exploratory physiological and temperature inputs. These signals support the interaction concept; they are not used to make a definitive judgement about emotion or health.'},
 {title:'Data report',tag:'03 / REVIEW',image:'/ecdysis/data-report.jpg',alt:'Ecdysis data report displayed on a phone',text:'The companion report brings current readings, recent records and explanatory notes into one place so that the user can review change rather than receive only a brief status prompt.'}
]
export default function Ecdysis(){const {zh,setZh}=useSiteLanguage();return <LanguageContext.Provider value={zh}><EcdysisContent zh={zh} setZh={setZh}/></LanguageContext.Provider>}
function EcdysisContent({zh,setZh}:{zh:boolean;setZh:(value:boolean)=>void}){const t=useTranslation();const [active,setActive]=useState(0);const [sensingTab,setSensingTab]=useState(0);const [materialOpen,setMaterialOpen]=useState(false);const position=useRef<{element:HTMLElement;offset:number}|null>(null);
function switchLanguage(){const sections=Array.from(document.querySelectorAll<HTMLElement>('.ecdysis-page section,.ec-footer'));const element=sections.find(el=>el.getBoundingClientRect().bottom>100);if(element)position.current={element,offset:element.getBoundingClientRect().top};setZh(!zh)}
useLayoutEffect(()=>{if(position.current){const {element,offset}=position.current;window.scrollBy({top:element.getBoundingClientRect().top-offset,behavior:'instant'});position.current=null}},[zh]);
return <Localize><main className="ecdysis-page" lang={zh?'zh-CN':'en'}><header className="ec-nav"><Link href="/">{t("Xiangrui Zhou")}</Link><nav><Link href="/#work">{t("Work")}</Link><Link href="/about">{t("About")}</Link><Link href="/#contact">{t("Contact")}</Link><button className="ec-language" type="button" onClick={switchLanguage} aria-label={zh?"Switch to English":"切换为中文"}><span lang="zh-CN" className={zh?"selected":""}>中</span><span aria-hidden="true">/</span><span lang="en" className={!zh?"selected":""}>EN</span></button></nav></header>
<section className="ec-hero"><div className="ec-hero-copy"><span className="ec-label">{t("04 / Graduation project · 2025")}</span><h1>{t("Ecdysis")}</h1><p className="ec-subtitle">{t("A more personal")}<br/>{t("relationship with care.")}</p><p>{t("A design exploration of sensing, physical feedback and digital continuity for everyday skin-health care.")}</p><a className="ec-button" href="#ec-context">{t("Discover the project ↓")}</a></div><div className="ec-hero-image"><Image src={`${path}hero.webp`} alt={t("Ecdysis modular handheld sensing device, product rendering")} fill priority sizes="(max-width:760px) 100vw, 60vw"/><span>{t("Sense. Understand. Care.")}</span></div></section>
<div className="ec-meta"><div><small>{t("Project")}</small>{t("Undergraduate graduation design")}<br/>{t("ShanghaiTech University · May 2025")}</div><div><small>{t("Designer / Advisor")}</small>{t("Xiangrui Zhou / Yue Zou")}</div><div><small>{t("Scope")}</small>{t("Research · Industrial design · Sensing prototype")}<br/>{t("Material exploration · Interface design")}</div></div>
<ChapterRail>{[['context','Research'],['insights','Research insights'],['system','System'],['form','Form & ergonomics'],['sensing','Sensing'],['material','Physical feedback'],['interface','Digital experience'],['journey','Complete journey'],['evaluation','Testing & reflection']].map(([id,title])=><a key={id} href={`#ec-${id}`}>{t(title)}</a>)}</ChapterRail>
<section className="ec-section" id="ec-context"><Heading n="01 / Understanding daily care" title="Care continues between appointments."/><ResearchIntro zh={zh}/></section>
<section className="ec-section ec-insights" id="ec-insights"><Heading n="Research insights" title="From observation to a design brief."/><div><div className="ec-insight-path">{["Observe change","Understand the experience","Connect the next step"].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{t(x)}</span></div>)}</div><div className="ec-cards"><article><h3>{t("Uncertainty")}</h3><p>{t("Changes can be difficult to interpret, making it hard to understand what is happening across a longer care journey.")}</p></article><article><h3>{t("Emotional burden")}</h3><p>{t("The case record showed concern and anxiety alongside physical changes, bringing emotional experience into the design brief.")}</p></article><article><h3>{t("Fragmentation")}</h3><p>{t("Observation, feedback and follow-up often sit in separate moments. The project explores a more connected experience.")}</p></article></div><p className="ec-note">{t("Design interpretation drawn from the case record and product review, rather than a clinical conclusion.")}</p></div></section>
<section className="ec-statement"><span className="ec-label">{t("The design question")}</span><h2>{t("How can sensing support")}<br/>{t("understanding,")}<br/>{t("as well as measurement?")}</h2></section>
<section className="ec-section ec-system-section" id="ec-system"><div className="ec-heading ec-system-heading"><span className="ec-label">{t("02 / System concept")}</span><h2>{t("Three moments. One care journey.")}</h2><p>{t("A proposed loop connects the handheld device, physical feedback and a companion app.")}</p><div className="ec-system-overview"><Image src="/ecdysis/system-map.png" width={882} height={712} alt={t("Detection, printing and mobile data flow")}/>{modules.map((m,i)=><button key={m.title} className={`zone-${i+1}`} aria-label={`${t("Highlight")} ${t(m.title)}`} aria-pressed={active===i} onClick={()=>setActive(i)}/>)}</div><p className="ec-note">{t("Select a part of the map to see that moment in detail.")}</p></div><div><div className="ec-switch" aria-label={t("Explore the system")}>{modules.map((m,i)=><button key={m.title} aria-pressed={active===i} onClick={()=>setActive(i)}>{String(i+1).padStart(2,'0')} · {t(m.title)}</button>)}</div><div className="ec-module-stage"><div className={`ec-system-media${systemVisuals[active].media.length>1?' is-pair':''}`}>{systemVisuals[active].media.map(item=><Image key={item.src} src={item.src} width={1600} height={1200} alt={t(item.alt)}/>)}</div><div className="ec-module"><span className="ec-label">{t(modules[active].tag)}</span><h3>{t(modules[active].title)}</h3><p>{t(modules[active].text)}</p></div></div><p className="ec-note">{t("The complete loop is a system proposal. The thesis records that remote printing integration was not yet completed.")}</p></div></section>
<section className="ec-form" id="ec-form"><Heading n="03 / Form & ergonomics" title="Designed around the hand.">{t("The form studies explored a stable grip, useful viewing distance and access to different areas of the body.")}</Heading><div className="ec-selection-board"><figure className="ec-product-detail"><Image src="/ecdysis/detail.webp" width={1600} height={1200} alt={t("Annotated Ecdysis rendering showing screen, button, sensor area and charging port")}/><figcaption>{t("Product architecture / controls, display and sensing surfaces.")}</figcaption></figure><figure className="ec-ergonomic-grid"><div><Image src="/ecdysis/ergonomic-grid.png" width={1188} height={1136} alt={t("Nine ergonomic model comparisons: diameter, grip and detachable handle")}/><i className="check-1" aria-label={t("Selected diameter")}>✓</i><i className="check-2" aria-label={t("Selected grip")}>✓</i><i className="check-3" aria-label={t("Selected handle")}>✓</i></div><figcaption>{t("Selected studies: the wider sensing head, cylindrical grip and straight detachable handle.")}</figcaption></figure></div><div className="ec-cards ec-form-findings"><article><span className="ec-label">{t("Compare")}</span><h3>{t("4, 5 and 6 cm")}</h3><p>{t("Three front diameters were compared alongside straight and tapered grip forms to explore size, balance and handling.")}</p></article><article><span className="ec-label">{t("Select")}</span><h3>{t("A modular grip")}</h3><p>{t("The selected study combined a 6 cm front with a removable cylindrical handle, 3 cm in diameter and 13 cm long.")}</p></article><article><span className="ec-label">{t("Refine")}</span><h3>{t("Soft light, clear form")}</h3><p>{t("A frosted front, metal transitions and a simple display create a calm visual language for an object intended for the home.")}</p></article></div></section>
<section className="ec-section ec-dark" id="ec-sensing"><Heading n="04 / Sensing prototype" title="Making an invisible process legible."/><div><p className="ec-lead">{t("The prototype connects visual recognition, physiological sensing and a readable data report so that each step can be reviewed rather than hidden.")}</p><div className="ec-sensing-tabs" aria-label={t("Explore the sensing prototype")}>{sensingPanels.map((panel,i)=><button key={panel.title} aria-pressed={sensingTab===i} onClick={()=>setSensingTab(i)}>{String(i+1).padStart(2,'0')} · {t(panel.title)}</button>)}</div><div className="ec-sensing-stage"><Image className={`ec-sensing-image is-${sensingTab+1}`} key={sensingPanels[sensingTab].image} src={sensingPanels[sensingTab].image} width={1800} height={1200} alt={t(sensingPanels[sensingTab].alt)}/><div><span className="ec-label">{t(sensingPanels[sensingTab].tag)}</span><h3>{t(sensingPanels[sensingTab].title)}</h3><p>{t(sensingPanels[sensingTab].text)}</p></div></div><p className="ec-note">{t("The visual and physiological modules were early prototypes. They were not trained or validated for clinical diagnosis, and their outputs remain sensitive to capture and testing conditions.")}</p></div></section>
<section className="ec-section" id="ec-material"><Heading n="05 / Material & expression" title="Care that leaves room for identity."/><div><p className="ec-lead"><button className="ec-inline-trigger" aria-expanded={materialOpen} aria-controls="ec-hydrogel-detail" onClick={()=>setMaterialOpen(open=>!open)}>{t("Hydrogel")}</button>{t(" printing was explored as a physical feedback format. The design asks how shape, translucency and colour could make a care object feel more personal.")}</p>{materialOpen&&<div className="ec-material-fold" id="ec-hydrogel-detail"><div><span className="ec-label">{t("MATERIAL BACKGROUND")}</span><h3>{t("A water-rich polymer network.")}</h3><p>{t("Hydrogels are three-dimensional networks of hydrophilic polymers. Their high water content and tunable softness make them useful for exploring moist, flexible and skin-adjacent material experiences.")}</p></div><div><span className="ec-label">{t("IN THIS PROJECT")}</span><h3>{t("A medium for physical feedback.")}</h3><p>{t("The Eazao Bio microfluidic 3D printer was used to test extrusion, colour and custom shapes. These samples explored form and expression; they were not tested as medicated dressings or therapeutic products.")}</p></div></div>}<Photo src="printing" className="ec-material-hero" alt="Hydrogel extrusion experiment on an Eazao Bio printer" caption="Material experiment / hydrogel printing with Eazao Bio."/><div className="ec-material-gallery"><figure><Image src="/ecdysis/hydrogel-purple.jpg" width={1100} height={1467} alt={t("Purple printed hydrogel sample")}/><figcaption>{t("Purple sample / extrusion and colour test.")}</figcaption></figure><figure><Image src="/ecdysis/hydrogel-orange.jpg" width={1100} height={1467} alt={t("Orange printed hydrogel sample")}/><figcaption>{t("Orange sample / form and drying test.")}</figcaption></figure><figure className="ec-hydrogel-overview"><Image src="/ecdysis/hydrogel-samples.jpg" width={1800} height={1350} alt={t("Printed hydrogel samples in different colours and shapes")}/><figcaption>{t("A wider set of customised samples.")}</figcaption></figure></div><div className="ec-two ec-material-notes"><article><h3>{t("What the material enabled")}</h3><p>{t("The experiments showed that colour and custom outlines could turn the printed response into a more personal and expressive object.")}</p></article><article><h3>{t("What still needs testing")}</h3><p>{t("No drug-loading experiment was conducted. Air-drying and fixation took considerable time, and further work is needed on material stability, skin safety, wear duration and a repeatable printing workflow.")}</p></article></div></div></section>
<section className="ec-interface" id="ec-interface"><Heading n="06 / Digital continuity" title="A place to see the bigger picture.">{t("A companion interface brings the daily check, device state, customisation and longer-term records into a single experience.")}</Heading><div className="ec-two"><Photo src="app" alt="Ecdysis high-fidelity mobile interface designs" caption="Mobile interface prototype / overview, device controls and personal records."/><div className="ec-app-list">{[['01','Home','A daily overview, recent measurements and reminders to check in.'],['02','Devices','Device status and proposed controls for choosing printed shapes and colours.'],['03','Statistics','Periodic records and trend views to support reflection over time.'],['04','Profile','Health-profile editing, device management and privacy settings.']].map(([n,appTitle,d])=><article key={appTitle}><span>{n}</span><div><h3>{t(appTitle)}</h3><p>{t(d)}</p></div></article>)}</div></div></section>
<section className="ec-journey-section" id="ec-journey"><div className="ec-journey-copy"><Heading n="07 / Complete journey" title="From a daily check to a connected loop.">{t("The complete scenario connects the interface, sensing device, personalised physical feedback and later reflection.")}</Heading><p className="ec-note">{t("The sequence brings the screen, sensing device and personalised physical response into one continuous experience, then returns the result to the longer-term record.")}</p></div><figure className="ec-journey-flow"><Image src="/ecdysis/journey.webp" width={2400} height={1990} alt={t("Eight-step Ecdysis scenario connecting phone, sensing device and physical feedback")}/><figcaption>{t("Envisioned experience / from a daily check to personalised physical feedback.")}</figcaption></figure></section>
<section className="ec-section" id="ec-evaluation"><Heading n="08 / Testing & reflection" title="What the prototype taught me."/><div><p className="ec-lead">{t("An initial interaction test with three participants explored the sequence of image capture, sensor collection and interface prompts.")}</p><div className="ec-cards"><article><h3>{t("Operation")}</h3><p>{t("The thesis reports that participants could complete the sequence independently after an initial introduction.")}</p></article><article><h3>{t("Feedback")}</h3><p>{t("Start, completion and abnormal-state sound cues were described as understandable in the initial test.")}</p></article><article><h3>{t("Image limits")}</h3><p>{t("The early recognition approach remained constrained by the macro camera’s resolution and operating conditions.")}</p></article></div><p className="ec-note">{t("This was a small formative evaluation using adapted usability questions, not a standard SUS score or evidence of clinical accuracy.")}</p><div className="ec-outcomes"><h3>{t("Built & explored")}</h3><p>{t("Ergonomic models, product renders, sensing hardware integration, rule-based image processing, hydrogel printing experiments and a high-fidelity interface prototype.")}</p><h3>{t("Still to validate")}</h3><p>{t("Long-term use, sensing robustness, material safety and the full device-to-print workflow. Predictive AI remained a theoretical framework without a trained, real-user learning loop.")}</p></div><a className="ec-film-link" href="https://youtu.be/6A4KnpBxx0o" target="_blank" rel="noreferrer"><span><small>{t("Full project film")}</small><strong>{t("Watch Ecdysis in full")}</strong></span><i aria-hidden="true">↗</i></a></div></section>
<footer className="ec-footer"><span className="ec-label">{t("Ecdysis / Xiangrui Zhou")}</span><h2>{t("From sensing the body")}<br/>{t("to understanding care.")}</h2><div><Link className="ec-button" href="/#work">{t("← Back to work")}</Link><a href="#">{t("Back to top ↑")}</a></div></footer></main></Localize>}
