'use client'
import {useState} from 'react'
import Image from 'next/image'
import {ChineseTitle} from '@/components/site-language'
export function ResearchIntro({zh}:{zh:boolean}){
 const [desk,setDesk]=useState(false)
 const [caseOpen,setCaseOpen]=useState(false)
 const say=(en:string,cn:string)=>zh?cn:en
 const stages=[['A','3','Onset','初始','Scattered red spots · slight itch','分散红点 · 轻微瘙痒','Little concern','无感'],['B','3','Intensification','加剧','Raised red spots · stronger itch','红点突起 · 明显瘙痒','Uncertainty and worry','疑惑、担心'],['C','4','Spread','扩散','Joined redness · intense itch','连片红肿 · 剧烈瘙痒','Anxiety','焦虑'],['D','2','Exudation','渗出','Local discharge · less itch','局部渗出 · 痒感减弱','Fear and loss of control','失控、害怕'],['E','4','Easing','缓解','Redness subsides · slight itch','红肿吸收 · 轻微瘙痒','More settled','逐渐趋稳'],['F','20','Recovery','恢复','Pigmentation · little sensation','色素沉着 · 无明显感觉','Gradually forgotten','逐渐淡忘']]
 return <div className="ec-research-intro">
 <p className="ec-lead">{say('The project begins with ','项目以')}<button className="ec-inline-trigger" aria-expanded={desk} aria-controls="ec-desk-detail" onClick={()=>{setDesk(!desk);setCaseOpen(false)}}>{say('neurodermatitis','神经性皮炎')}</button>{say(' and explores how people understand changing skin symptoms and sustain everyday care.','为切入点，探索人们如何理解不断变化的皮肤状态，并长期维持日常护理习惯。')}</p>
 {desk&&<section id="ec-desk-detail" className="ec-research-fold" aria-label={say('Desk research','桌面调研')}>
 <span className="ec-label">{say('DESK RESEARCH / THE CONDITION','桌面调研 / 疾病背景')}</span>
 <h3>{say('What is neurodermatitis?','什么是神经性皮炎？')}</h3>
 <p>{say('Also called lichen simplex chronicus, it often begins with one or two persistently itchy patches. Repeated scratching or rubbing can thicken the skin and sustain an itch–scratch cycle. It is not contagious.','神经性皮炎也称慢性单纯性苔藓，常从一两处持续瘙痒的皮肤斑块开始。反复抓挠或摩擦会让皮肤增厚，并维持“瘙痒—抓挠”的循环。它不具有传染性。')}</p>
 <div className="ec-condition-map"><Image src="/ecdysis/neurodermatitis-sites.png" width={442} height={920} alt={say('Body map showing common sites of neurodermatitis','神经性皮炎常见部位示意图')}/><div><span className="ec-label">{say('COMMON SITES','常见部位')}</span><h4>{say('It often appears where the skin can be repeatedly rubbed or scratched.','常出现在容易反复摩擦或抓挠的位置。')}</h4><p>{say('The project material highlights the sides of the neck, back and lower back, wrists, genital area and ankles. The exact location and appearance vary from person to person.','项目材料标出了颈侧、背部与下背部、手腕、生殖区域及脚踝。具体位置和表现会因人而异。')}</p></div></div>
 <figure className="ec-research-visual"><Image src="/ecdysis/research-evidence.jpg" width={2400} height={536} alt={say('Original research board: participant account, skin–stress literature and skin detection tools','原始调研图：个案反馈、皮肤与压力文献、皮肤检测工具')}/><figcaption>{say('Original project research · lived experience, literature and existing tools.','项目原始调研素材 · 个案体验、文献与现有工具。')}</figcaption></figure>
 <div className="ec-fold-columns"><div><h4>{say('Skin and stress','皮肤与压力')}</h4><p>{say('Itch can interrupt sleep and daily activities. Stress may accompany or worsen symptoms, while the discomfort can add to emotional strain.','瘙痒会干扰睡眠与日常活动。压力可能伴随或加重症状，而持续的不适也会增加情绪负担。')}</p></div><div><h4>{say('Beyond a single measurement','从单次检测到连续理解')}</h4><p>{say('The project asks how records and feedback can help people understand change over time and connect it to everyday care.','项目由此关注：如何通过连续记录与易理解的反馈，帮助人们理解变化，并连接日常护理。')}</p></div></div>
 <p className="ec-note">{say('Medical background: ','疾病背景：')}<a href="https://www.aad.org/public/diseases/eczema/types/neurodermatitis" target="_blank" rel="noreferrer">American Academy of Dermatology ↗</a></p>
 </section>}
 <button className="ec-stat ec-stat-trigger" aria-expanded={caseOpen} aria-controls="ec-case-detail" onClick={()=>{setCaseOpen(!caseOpen);setDesk(false)}}><strong>1</strong><span className="ec-stat-copy"><b>{say('longitudinal case study','位个案的持续跟踪')}</b><small>{say('August–September 2024','2024 年 8—9 月')}</small></span><strong>6</strong><span className="ec-stat-copy"><b>{say('stages of change','个症状变化阶段')}</b><small>{say('From onset to recovery','从初始发作到恢复')}</small></span><i aria-hidden="true">{caseOpen?'−':'+'}</i></button>
 {caseOpen&&<section className="ec-research-fold" id="ec-case-detail" aria-label={say('Case study','个案研究')}><><span className="ec-label">{say('LONGITUDINAL CASE STUDY','个案跟踪研究')}</span><h2><ChineseTitle>{say('Symptoms change. Feelings do, too.','变化的不只有皮肤，还有感受。')}</ChineseTitle></h2><p>{say('The thesis documents one 23-year-old woman with seasonal recurrence, followed during August–September 2024. The affected area was above the right ankle. The record paired skin changes with itch, emotions and care actions.','论文记录了 2024 年 8—9 月对一位有季节性复发经历的 23 岁女性的跟踪。此次发作位于右脚踝上方，同步观察皮肤变化、瘙痒感受、情绪与护理行为。')}</p><figure className="ec-case-photos"><Image src="/ecdysis/case-0.jpg" width={1256} height={251} alt={say('Case photographs: stages A to C','个案照片：A 至 C 阶段')}/><Image src="/ecdysis/case-1.jpg" width={1259} height={251} alt={say('Case photographs: stages D to F','个案照片：D 至 F 阶段')}/><figcaption>{say('Thesis Fig. 2-1 · left to right, A–C above and D–F below.','论文图 2-1 · 从左至右，上排 A—C，下排 D—F。')}</figcaption></figure><div className="ec-stage-grid">{stages.map(([id,days,en,cn,body,cbody,emotion,cemotion])=><article key={id}><small>{id} / {days} {say('days','天')}</small><h3>{say(en,cn)}</h3><p>{say(body,cbody)}</p><b>{say(emotion,cemotion)}</b></article>)}</div><p>{say('Early changes were initially left untreated. As discomfort and anxiety increased, the record moved from self-directed responses to seeking care. The design implication is to make the course of change easier to review, rather than relying on memory or a single reading.','记录中，早期变化未被处理；随着不适和焦虑加重，应对行为从自行处理转向就医。由此得到的设计启发是：帮助使用者回顾一段连续的变化，而非仅依赖记忆或某次检测。')}</p><p className="ec-note">{say('Source: thesis §2.1, Fig. 2-1 and Table 2-1 (printed p. 4). This is one qualitative record, not a typical disease course or a clinical study.','来源：论文 2.1 节、图 2-1 和表 2-1（正文第 4 页）。这是单一个案的质性记录，不代表典型病程或临床研究结论。')}</p></></section>}
 <p className="ec-note">{say('A qualitative observation of physical sensations, emotions and care behaviours, used as a design reference rather than a clinical study.','这项质性观察记录身体感受、情绪与护理行为的变化，为设计提供线索，并非临床研究。')}</p>
 </div>
}
