export type Chapter = {
 id: string
 label: string
 title: string
 intro: string
 cards?: {title: string; text: string; image?: string}[]
 steps?: {title:string; text:string; images?: string[]}[]
 image?: {id:string; title:string; detail:string; assets?: string[]}
 note?: string
}
export const quipuChapters: Chapter[] = [
 {id:'memory',label:'02 / The problem',title:'What makes a memory stay?',intro:'You are recalling graduation day ten years later. Which object brings the scene back more vividly: a group photo, or a uniform filled with handwritten names? The comparison reveals why physical traces often hold more emotional detail than perfectly stored digital information.',cards:[{title:'Information explosion',text:'Constant input makes filtering difficult and weakens the efficiency of remembering.',image:'/quipu/new-assets/问题1信息爆炸.png'},{title:'Superficial connections',text:'Frequent contact can still feel shallow when communication has no tangible trace.',image:'/quipu/new-assets/superficial connections.png'},{title:'Emotional simplification',text:'Standardised reactions compress complex emotions into a small set of convenient signals.',image:'/quipu/new-assets/emotional simplification.png'}]},
 {id:'ritual',label:'03 / Design direction',title:'A ritual for the digital age.',intro:'Quipu creates a bridge across time: an ancient, physical method of knotting becomes the entry point to contemporary language processing. Technology stays behind the experience while the rope, gesture and shared projection remain visible.',cards:[{title:'Semiotics',text:'Knot, colour and position work as a language before written language.',image:'/quipu/new-assets/semiotics.svg'},{title:'Emotional connection',text:'A slow physical action gives personal stories weight and duration.',image:'/quipu/new-assets/spirit.svg'},{title:'Media link',text:'The installation connects body, object, speech and projected response.',image:'/quipu/new-assets/media link icon.svg'}]},
 {id:'interaction',label:'04 / Interaction',title:'A knot becomes a conversation.',intro:'Participants complete the experience in three clear stages. As they move down the page, the highlighted stage follows their progress and the photographs show what happens at each point.',steps:[{title:'Take a cord',text:'Choose an auxiliary rope and learn the simple rule of the installation.',images:['/quipu/new-assets/step1-1.png','/quipu/new-assets/step1-2.png']},{title:'Tie & speak',text:'Tie the cord onto the main rope while speaking a thought, feeling or memory.',images:['/quipu/new-assets/step2-1.png','/quipu/new-assets/step2-2.png']},{title:'Wait & read',text:'Wait for the system to interpret the input, then inspect the projected response and the collective rope.',images:['/quipu/new-assets/step3-2.png','/quipu/new-assets/step3-3.png']}]},
 {id:'system',label:'05 / System',title:'A quiet system behind the ritual.',intro:'The experience links a participant, an RFID-tagged cord, speech recognition, language processing, lighting and projection. Each layer supports the ritual without competing with it.',cards:[{title:'Input',text:'RFID and audio identify the interaction and collect the participant’s spoken story.'},{title:'Processing',text:'Python and language models classify and associate the content.'},{title:'Output',text:'ESP32, lighting and projection return a visible response to the shared space.'}],image:{id:'Q05',title:'Hardware–software system',detail:'From physical input to collective visual response.',assets:['/quipu/new-assets/system map.png']}},
 {id:'technology',label:'06 / Technology',title:'From sensing to expression.',intro:'The prototype was developed through repeated tests of two connected groups: the rope and sensing hardware, and the projected screen. Together they translate a tactile action into a changing visual field.',cards:[{title:'Rope & RFID',text:'Tags embedded in auxiliary ropes trigger different interaction states and connect the participant to the system.',image:'/quipu/new-assets/感应-rfid-person.png'},{title:'Screen & projection',text:'Visual tests explored how words, colour and movement could become a legible collective response.',image:'/quipu/new-assets/screen - visual test1.png'}],image:{id:'Q06',title:'Technology studies',detail:'Sensing, transmission, code and projection tests.',assets:['/quipu/new-assets/感应-rfid.png','/quipu/new-assets/感应-rfid4.png','/quipu/new-assets/screen - code.png','/quipu/new-assets/screen- projector.png']}},
 {id:'prototype',label:'07 / Prototype',title:'Making the interaction tangible.',intro:'Material and construction tests shaped the way participants handled the installation. Rope structures, light transmission and suspended assembly were refined together.',cards:[{title:'Rope & weave',text:'Material and knotting trials informed the cylindrical main rope and open-ended auxiliary cords.'},{title:'Light & atmosphere',text:'Optical fibre and LED tests made interaction states visible without adding another screen.'}],image:{id:'Q07',title:'Prototype iterations',detail:'Rope, light and assembly prototypes.',assets:['/quipu/new-assets/prototype1.png','/quipu/new-assets/prototype1-3.png','/quipu/new-assets/prototype2-1.png','/quipu/new-assets/prototype2-3.png']}},
 {id:'exhibition',label:'08 / Exhibition',title:'Individual stories. Collective memory.',intro:'Visitors tied cords, narrated stories and watched the shared projection grow. The installation brought ancient recording gestures into contact with contemporary information processing.',cards:[{title:'What was made',text:'A working installation connected rope, sensing, light, spoken input and shared projection.'},{title:'What it opens up',text:'The work asks how personal experiences become collective memory and continue to hold meaning after the interaction ends.'}],image:{id:'Q08',title:'Quipu in exhibition',detail:'The final installation and visitor interactions.',assets:['/quipu/new-assets/exhibition.png','/quipu/new-assets/exhibition3.png','/quipu/new-assets/exhibition4.png']},note:'The exhibition produced qualitative feedback and observations; further study would be needed to measure emotional impact.'}
]
export const auraChapters: Chapter[] = [
 {id:'context',label:'01 / Background',title:'Less to do. Less engaged.',intro:'When active driving tasks decrease, sustained attention can become difficult. The project focuses on how a cabin experience might respond to that reduced engagement.',cards:[{title:'Active fatigue',text:'Dense traffic and frequent acceleration or braking place demands on the driver. The research distinguishes this workload from fatigue caused by low stimulation.'},{title:'Passive fatigue',text:'Monotonous roads, a fixed posture and long periods without interaction create a different challenge: maintaining engagement when there is little to do.'},{title:'Design opportunity',text:'Use changes in music and, at higher fatigue levels, tactile feedback to create a graded response rather than a single repeated alert.'}]},
 {id:'journey',label:'02 / Journey research',title:'Energy changes along the road.',intro:'A documented journey from San Francisco to Los Angeles followed the experience of a driver and four passengers over about six and a half hours. The journey map connects activities, mood and physical discomfort across the trip.',steps:[{title:'Initial / excited',text:'Music, conversation, observation and photos accompanied an energetic start.'},{title:'Early / still energetic',text:'Some passengers slept or used their phones. Conversation became less frequent.'},{title:'Middle / sleepy',text:'Eye strain, muscle stiffness and loss of attention appeared as the journey continued.'},{title:'Late / tired',text:'Hunger, lower-back discomfort and restaurant searches became part of the experience.'},{title:'Final / exhausted',text:'Traffic, soreness and sleepiness shaped the final stretch.'}],image:{id:'A01',title:'A journey from excitement to fatigue',detail:'Original journey map and selected road-trip photographs. Wide landscape composition.'}},
 {id:'insight',label:'03 / Synthesis',title:'From surprise to response.',intro:'The experience analysis highlighted two memorable moments: discovering unexpected things and singing along to fitting music. Aura brings them together, using music as the carrier for moments of surprise.',cards:[{title:'A shared cabin experience',text:'The accounts describe music and conversation as central activities for both driver and passengers, while also showing different comfort levels and needs.'},{title:'An auditory starting point',text:'The concept prioritises sound so that its main interaction does not ask the driver to look at another visual display.'},{title:'A changing response',text:'Tempo, familiarity, vocal content, valence, intensity and rhythm stability informed the proposed music strategy.'}],image:{id:'A02',title:'From passenger accounts to a concept',detail:'Interview/experience-analysis board and the Surprise → Music concept diagram.'}},
 {id:'levels',label:'04 / Intervention concept',title:'One system. Different levels of support.',intro:'The concept uses PERCLOS—eyelid closure over time—as an input for fatigue classification. The proposed response progresses from music to tactile cues, then to an alert and a suggestion to stop.',steps:[{title:'Good',text:'The baseline state sits outside the three music-intervention levels.'},{title:'Mild',text:'The first music layer introduces a change in the listening experience.'},{title:'Moderate',text:'The second layer adjusts music characteristics, including tempo, familiarity and vocal content.'},{title:'Severe',text:'A stronger music layer is paired with vibration and driving nudges in the concept.'},{title:'Extreme',text:'An alert and parking or stopping suggestions replace music as the main response.'}],note:'These are the project’s proposed intervention states, not validated fatigue thresholds or driving guidance.'},
 {id:'hierarchy',label:'05 / Hierarchical system',title:'Sense. Assess. Respond.',intro:'Aura follows one continuous chain: read the driver’s eyelid behaviour, translate it into a fatigue level, then match that level with a proportionate intervention.'},
 {id:'interface',label:'06 / Interface',title:'A presence within the cabin.',intro:'The interface combines a fatigue-level prompt in the driving dashboard with an Aura area in the central display. Music information and the current attention state sit within the wider in-car experience.',cards:[{title:'Make the state legible',text:'The dashboard communicates the current fatigue classification, while the central display connects it to the music experience.'},{title:'Create a surprise moment',text:'The concept explores changes, pauses and alerts in the audio as distinct cues rather than one unchanging warning.'},{title:'Add tactile feedback',text:'The steering-wheel concept explores vibration with music beats and directional driving cues at the more intensive intervention level.'}],image:{id:'A03',title:'Aura dashboard & central display',detail:'Clean interface exports: dashboard, central screen and fatigue-state variations. Prefer editable originals or 2× PNGs.'}},
 {id:'prototype',label:'07 / Technical implementation',title:'From a system map to a working demo.',intro:'My role covered defining and consolidating the core concept, integration and technical implementation. The exhibition prototype combined a model steering wheel, vibration feedback, a display and selectable road-condition scenarios.',cards:[{title:'Detection feasibility',text:'Camera, Python and Dlib were used to explore eye tracking and PERCLOS. Ordinary-camera instability meant the exhibition used manual fatigue-mode switching.'},{title:'Music processing',text:'The technical exploration included tempo analysis with Librosa, vocal-content processing and valence classification, followed by music screening and selection.'},{title:'Connected hardware',text:'A 3D-printed steering-wheel model, vibration control and Bemfa communication connected the physical feedback to the software demonstration.'},{title:'Interactive simulation',text:'Pre-prepared road videos and mode buttons allowed visitors to move between conditions and experience the corresponding feedback.'}],image:{id:'A04',title:'Building the Aura prototype',detail:'Steering-wheel CAD/render, 3D printing, assembly, vibration components and the technical system diagram.'}},
 {id:'exhibition',label:'08 / Exhibition',title:'A prototype to learn from.',intro:'The staged exhibition recreated a simplified in-car space. Visitors could turn the steering wheel, experience vibration and switch road conditions to explore Aura’s different feedback levels.'},
 {id:'future',label:'09 / Future',title:'Closer to the road.',intro:'The next phase connects Aura to richer listening data and tests the complete experience in a more realistic driving environment.'}
]
